name: build
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - run: |
          git branch -d buildbot
          git checkout main
          git checkout -b buildbot

      - name: Build
        run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build distribution package
          branch: buildbot
          push_options: "--force"
          skip_dirty_check: true
          skip_fetch: true

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          base: gh-pages
          branch: buildbot
          commit-message: Built Site with GitHub Actions
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          title: "Update dist build"
          body: Update dist folder with latest changes
          labels: |
            automated pr
          assignees: xaviergmail

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
