name: build
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: dist
          author_name: Xavier Bergeron
          author_email: xavbergeron@gmail.com
          branch: buildbot

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          base: main
          branch: buildbot
          commit-message: Build site
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          title: 'Update dist build'
          body: Update dist folder with latest changes
          labels: |
            automated pr
          assignees: xaviergmail

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"